
H = 9
W = 16
TILE_EXPAND_RADIUS = 2

STATUS_BUFFERING = 0
STATUS_STREAMING = 1
STATUS_EXCESS = 2


NETWORK_STATUS_IDLE = 0
NETWORK_STATUS_REQUESTING = 1
NETWORK_STATUS_RECEIVING = 2
NETWORK_STATUS_DONE = 3

STEP = 0.01 #10 miliseconds is the smallest grain steps

FILE_PATH_SDS = './salient_ds_dict_w16_h9'
